### ISSUE TITLE
[BUG] Small buttons are too big on a 123DPI screen when used with small titlebar. Regular sizes seem to be to big in general.

### ISSUE THREAD

**Issue by Kiffmet** [n4n0GH/hello#42] opened 2019-12-04 18:56 UTC
**Describe the bug**
See title. The simplest fix would be to be able to specify button size and titlebar height in pixels, and not as preset. My system DPI are set by specifying panel dimensions in xorg.conf.d. No scaling/fractional scaling settings within KDE system settings.

/etc/X11/xorg.conf.d/20-monitor.conf

Section "Monitor"
    Identifier             "DisplayPort-0"
    DisplaySize             526.85 296.35    # In millimeters
EndSection

The monitor used is an Agon AG241QX 24'' 2560x1440.

**Additional files**
![Titlebars](https://user-images.githubusercontent.com/14188195/70171679-82fecf00-16cf-11ea-9e91-0ce27772876e.png)

**Comment by n4n0GH** [comment] 2019-12-04 20:15
So first of all, this is behaviour I was aiming for; the pixel dimensions are exactly the same on macOS Mojave, where the buttons are 24px in width and height. Since macOS uses a scaling method to "shrink" the rendered view, the buttons will appear as 12px instead. 
I might have to actually move to a direct number input instead of a dropdown selector so this can be fine-tuned on other DPI settings. I really don't wanna though because inputs are ugly. But oh well if it can't be helped.

**Comment by Kiffmet** [comment] 2019-12-04 23:25
Thanks a lot! I really appreciate it.

**Comment by n4n0GH** [comment] 2019-12-05 10:26
Can you pull the newest version (see 6393828) and check if that works on your DPI settings?

**Comment by Kiffmet** [comment] 2019-12-05 14:20
Works perfectly, although I still think that the "regular" titlebar is too large. Can you also make that setting pixellized?
![Titlebars2](https://user-images.githubusercontent.com/14188195/70243374-be060e80-1772-11ea-8dc2-195b9662618a.png)

**Comment by n4n0GH** [comment] 2019-12-05 14:40
> Can you pixellize corner radius and titlebar height (regular still seems to big) settings aswell?

Yes, absolutely. Was going to do that once you confirmed that the button stuff worked out for you. Thanks for checking it out so far.

**Comment by n4n0GH** [comment] 2019-12-06 07:37
@Kiffmet Please try again with b7bfcc3

**Comment by Kiffmet** [comment] 2019-12-06 14:50
Titlebar margin doesn't seem to work correctly. When setting it to 1px, I get a titlebar size that corresponds to the previous "small" setting, but nearly all of the titlebar is the "resize window" handle. The handle for moving the window is 1px in size. When setting the titlebar margin to 8px, I get the following result:

![Screenshot_20191206_154638](https://user-images.githubusercontent.com/14188195/70331633-17883f00-1840-11ea-9287-39a57805c21f.png)

Window corner rounding seems to work fine.

**Comment by n4n0GH** [comment] 2019-12-06 15:54
I'm unable to reproduce your issue. No matter my settings, the resize handle is only formed when hovering over or on the outside of the window.

**Comment by Kiffmet** [comment] 2019-12-06 18:01
I can confirm that it works as intended when I remove my 20-monitor.conf. If you start your xserver with the "-dpi 124" option, you should be able to reproduce the issue.

**Comment by n4n0GH** [comment] 2019-12-07 08:21
> The funny thing is, that the titlebar did not do that, when it was still using presets, maybe that's a useful hint for you.

That's odd indeed, seeing how I just changed the source of the number being used in some functions. I need to check out if the type was different before (it's using qreal now). Then again I also didn't change the way the "?" icon was drawn from how Breeze does it and it still bugged out #3 :^)

Also thanks for the hint how to debug for hidpi myself. Will try that out on a seperate machine I'll be setting up for cross checks.

**Comment by n4n0GH** [comment] 2020-01-30 22:38
Closing this as I most likely won't be working on this any further (see 5f57998e).

**Closed by n4n0GH** 2020-01-30 22:38 UTC
Labels: bug, question
